plugins:
 - serverless-plugin-utils

service: express-app
 
provider:
  name: aws
  runtime: nodejs18.x
  vpc:
    securityGroupIds: ${split(${env:SECURITY_GROUP_IDS}, ',')}
    subnetIds: ${split(${env:SUBNET_IDS}, ',')}
  stage: dev
  region: us-east-2
 
functions:
  app:
    handler: app.handler
    events:
      - http: 
          path: /oaks
          method: any
          cors: true
      - http: 
          path: /{proxy+}
          method: any
          cors: true
