plugins:
  - serverless-plugin-utils

service: express-app

provider:
  name: aws
  runtime: nodejs18.x
  vpc:
    securityGroupIds: ${split(${env:SECURITY_GROUP_IDS}, ',')}
    subnetIds: ${split(${env:SUBNET_IDS}, ',')}
  stage: dev
  region: us-east-2

functions:
  app:
    environment:
      RDS_DB_HOST: ${aws:ssm:/CODA_DB_HOST}
      RDS_DB_NAME: ${aws:ssm:/CODA_DB_NAME}
      RDS_PASSWORD: ${aws:ssm:/CODA_DB_PASSWORD}
      RDS_USERNAME: ${aws:ssm:/CODA_DB_USERNAME}
    handler: app.handler
    events:
      - http:
          path: /{proxy+}
          method: GET
          cors: true
      - http:
          path: /{proxy+}
          method: POST
          cors: true
          authorizer:
            name: authorizerFunc
            type: token
  authorizerFunc:
    environment:
      AUTH0_AUDIENCE: ${aws:ssm:/CODA_AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${aws:ssm:/CODA_AUTH0_DOMAIN}
    handler: auth.handler
