plugins:
 - serverless-plugin-utils

service: express-app
 
provider:
  name: aws
  runtime: nodejs18.x
  vpc:
    securityGroupIds: ${split(${env:SECURITY_GROUP_IDS}, ',')}
    subnetIds: ${split(${env:SUBNET_IDS}, ',')}
  stage: dev
  region: us-east-2
 
functions:
  app:
    handler: app.handler
    events:
      - http: 
          path: /{proxy+}
          method: any
          cors: 
            origin: 'https://coda.phytosphere.com' //if making a request using credentials, the wildcard valeu is not allow for Access-Control-Allow-Origin header
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              allowCredentials: true
